- type: markdown
  attributes:
    value: "**MAKE SURE YOU READ THE CONTRIBUTION GUIDE FOR INFORMATION ABOUT CODE FORMATTING AND BRANCH NAMING CONVENTIONS**"

- type: dropdown
  attributes:
    label: Host OS
    description: Which operating system was this tested on?
    multiple: false
    options:
      - Windows
      - MacOSX
      - Linux
      - BSD
    validations:
      required: true
      
- type: dropdown
  attributes:
    label: Compiler 
    description: Which compiler was this tested with?
    multiple: true
    options:
      - GCC
      - Clang
    validations:
      required: true

- type: textarea
  attributes:
    label: Description of changes
    description: Explain what changes or additions/deletions you made in this PR.
    validations:
      required: true
